default: &default  
  adapter: postgresql
  encoding: unicode
  #username: postgres
  database: <%= ENV["DATABASE_URL"] %>
  #host: localhost
 # port: 3000
 # host: <%= ENV['BLOG_DB_1_PORT_5432_TCP_ADDR'] %>
 # port: <%= ENV['BLOG_DB_1_PORT_5432_TCP_PORT'] %>
  pool: 5

#production:
#  encoding: utf8
#  pool: 15

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
  database: DATABASE_URL
  #username: postgres

development:  
  <<: *default
  database: DATABASE_URL
  #database: demo_development
 # username: postgres

test:  
  <<: *default
  database: DATABASE_URL
  #database: demo_test
